export const languages = [
  { id: 'en', name: 'English', flag: '/images/flags/english-flag.png' },
  { id: 'sp', name: 'Spanish', flag: '/images/flags/spain-flag.png' },
];

export const regions = [
  { id: 'af', name: 'Africa' },
  { id: 'as', name: 'Asia' },
  { id: 'eu', name: 'Europe' },
  { id: 'la', name: 'Latin America' },
  { id: 'me', name: 'Middle East' },
  { id: 'na', name: 'North America' },
  { id: 'ot', name: 'Others' },
];

export const ageRange = [
  { id: 0, value: '18-24' },
  { id: 1, value: '25-29' },
  { id: 2, value: '30-34' },
  { id: 3, value: '35-39' },
  { id: 4, value: '40-45' },
];

export const genders = [
  { id: 'f', value: 'Female' },
  // { id: 'm', value: 'Male' },
];

export const credits = [
  { id: '20', value: '0-20 credits/min' },
  { id: '30', value: '20-30 credits/min' },
  { id: '40', value: '30-40 credits/min' },
  { id: '100', value: '40-100 credits/min' },
];

export const listValues = [
  {
    id: 0,
    name: 'Vanessa',
    age: '26',
    credits: '30',
    country: 'brazil',
    languages: 'English, Portuguese',
    online: true,
    image: '',
    availiblity: true,
  },
  {
    id: 1,
    name: 'Eroticbitch',
    age: '23',
    credits: '20',
    country: 'nigeria',
    languages: 'English',
    online: true,
    image: '',
    availiblity: false,
  },
  {
    id: 2,
    name: 'Slutish pussy',
    age: '25',
    credits: '15',
    country: 'us',
    languages: 'English',
    online: true,
    image: '',
    availiblity: false,
  },
  {
    id: 3,
    name: 'Sammy',
    age: '35',
    credits: '20',
    country: 'colombia',
    languages: 'Espanhol',
    online: true,
    image: '',
    availiblity: false,
  },
  {
    id: 4,
    name: 'Laura',
    age: '22',
    credits: '30',
    country: 'colombia',
    languages: 'Colombiano',
    online: true,
    image: '',
    availiblity: false,
  },
  {
    id: 5,
    name: 'Eliza',
    age: '32',
    credits: '25',
    country: 'brazil',
    languages: 'Brasil',
    online: true,
    image: '',
    availiblity: false,
  },
  {
    id: 6,
    name: 'Dalilla',
    age: '25',
    credits: '25',
    country: 'brazil',
    languages: 'English, Ingles, Inglês E Português, Portuguese, Português',
    online: true,
    image: '',
    availiblity: true,
  },
  {
    id: 7,
    name: 'Valeria',
    age: '19',
    credits: '30',
    country: '',
    languages: 'Español',
    online: true,
    image: '',
    availiblity: false,
  },
  {
    id: 8,
    name: 'Phoenix',
    age: '40',
    credits: '29.5',
    country: 'brazil',
    languages: 'Colombiano, English, Español, Português, Venezuela',
    online: true,
    image: '',
    availiblity: false,
  },
  {
    id: 9,
    name: 'Mara',
    age: '25',
    credits: '25',
    country: 'brazil',
    languages:
      '24, Abkhazian, Afar, Afrikaans, Akan, Albanian, American, Amharic, Arabic, Aragonese, Armenian, Assamese, Australia, Avaric, Avestan, Aymara, Azerbaijani, Bambara, Bangladesh, Bashkir, Basque, Belarusian, Belgica, Bengali, Bihari languages, Bislama, Bokmål, Norwegian; Norwegian Bokmål, Bosnian, Brasileño, Breton, British, Bulgarian, Burmese, Catalan; Valencian, Central Khmer, Chamorro, Chechen, Chichewa; Chewa; Nyanja, Chinese, Chi na, Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic, Chuvash, Colombiano, Colombino, Cornish, Corsican, Cree, Croatian, Czech, Danish, Deutsch, Divehi; Dhivehi; Maldivian, Dutch, Dutch; Flemish, Dzongkha, Eeuu, English, English - Spanish, English-tagalog, Enugu, Espanhol, Españo, Español, Esperanto, Estonian, Ethiopia, Ewe, Faroese, Fijian, Filifino, Filipino, Finnish, Français, French, French -english, Fulah, Gaelic; Scomttish Gaelic, Galician, Ganda, Georgian, German, Greek, Greek, Modern (1453-), Guadalajara, Guarani, Gujarati, Haitian; Haitian Creole, Hausa, Hebrew, Herero, Hfrghh, Hindi, Hiri Motu, Hungarian, I Can Learn Your Language If You Want 😉, Icelandic, Ido, Igbo, Indonesian, Ingles, Inglês E Português, Interlingua (International Auxiliary Language Association), Interlingue; Occidental, Inuktitut, Inupiaq, Irish, Italian, Jap, Japanese, Japon, Javanese, Kalaallisut; Greenlandic, Kannada, Kannada  English, Kanuri, Kashmiri, Kazakh, Ke, Kikuyu; Gikuyu, Kinyarwanda, Kirghiz; Kyrgyz, Komi, Kongo, Korean, Kuanyama; Kwanyama, Kurdish, Lao, Latin, Latvian, Limburgan; Limburger; Limburgish, Lingala, Lithuanian, Luba-Katanga, Luxembourgish; Letzeburgesch, Macedonian, Malagasy, Malay, Malayalam, Malaysia, Maltese, Manx, Maori, Marathi, Marshallese, Mexican, Mongolian, Nauru, Navajo; Navaho, Ndebele, North; North Ndebele, Ndebele, South; South Ndebele, Ndonga, Nemet, Nepali, Northern Sami, Norwegian, Norwegian Nynorsk; Nynorsk, Norwegian, Occitan (post 1500), Ojibwa, Oriya, Oromo, Ossetian; Ossetic, Pakistan, Pali, Panjabi; Punjabi, Persian, Philippines, Polish, Portugal, Português, Prsia, Pushto; Pashto, Quechua, Québec, Romana, Romanian; Moldavian; Moldovan, Romansh, Rundi, Russian, Samoan, Sango, Sanskrit, Sardinian, Serbian, Shona, Sichuan Yi; Nuosu, Sindhi, Sinhala; Sinhalese, Slovak, Slovenian, Somali, Sotho, Southern, Spain, Spanish, Spanish; Castilian, Sundanese, Swahili, Swati, Swedish, Tagagalog, Tagalog, Tagalog English, Tahitian, Tajik, Tamil, Tatar, Telugu, Thai, Tibetan, Tigrinya, Tonga (Tonga Islands), Tsonga, Tswana, Turkish, Turkmen, Twi, Uighur; Uyghur, Uk, Ukrainian, Urdu, Usa, Uzbek, Venda, Venezuela, Vietnamese, Volapük, Walloon, Welsh, Western Frisian, Wolof, Wu Chinese, Xhosa, Yiddish, Yoruba, Zhuang; Chuang, Zulu, เงี่ยน Sex, ไทย',
    online: true,
    image: '',
    availiblity: false,
  },
  {
    id: 10,
    name: 'Mia Loren',
    age: '43',
    credits: '25',
    country: 'brazil',
    languages: 'English, Espanhol, Inglês E Português, Portuguese',
    online: true,
    image: '',
    availiblity: false,
  },
];
